#DATA SCIENCE

# - PANDAS

- Pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.


Key Features
- Data cleaning and preprocessing
- Data filtering and sorting
- Handling missing values
- Data aggregation and grouping
- Merging and joining datasets
- Time-series analysis
- Reading and writing data from multiple formats (CSV, Excel, SQL, JSON, etc.)

#Common Pandas Components
- pandas.Series
- pandas.DataFrame
- pandas.Index



#Frequently Used Submodules
- pandas.io – Input/output operations
- pandas.plotting – Data visualization utilities
- pandas.testing – Testing utilities
- pandas.api – Public API extensions
- pandas.tseries – Time series functionality
- pandas.arrays – Extension array types



#Related Python Packages Commonly Used with Pandas
- NumPy – Numerical computing
- Matplotlib – Data visualization
- Scikit-learn – Machine learning
- SciPy – Scientific computing
- Seaborn – Statistical visualization
- OpenPyXL – Excel file handling
- SQLAlchemy – Database connectivity

In [1]:
#Load library
import pandas as pd

In [2]:
df = pd.DataFrame()

In [3]:
df['names'] = ['John','Rose','Jack']

In [4]:
df['age'] = [15,19,46]

In [5]:
df['country'] = ['Kenya','Uganda','Malawi']

In [6]:
df

  names  age country
0  John   15   Kenya
1  Rose   19  Uganda
2  Jack   46  Malawi

In [7]:
#Load library
import pandas as pd

# Create a DataFrame
df = pd.DataFrame(columns=['Name','Age','Country'],
                  data=[
                       ['John',19,'Kenya'],
                       ['Rebecca',16,'Uganda'],
                       ['Lisa',19,'Rwanda'],
                       ['Godfrey',19,'Tanzania'],
                       ['Vivian',19,'Burundi']
                      ])

#show DataFrame
df

      Name  Age   Country
0     John   19     Kenya
1  Rebecca   16    Uganda
2     Lisa   19    Rwanda
3  Godfrey   19  Tanzania
4   Vivian   19   Burundi

In [8]:
df.iloc[0]

Name        John
Age           19
Country    Kenya
Name: 0, dtype: object

In [9]:
type(df)

pandas.core.frame.DataFrame

Creating a Series

In [10]:
#Load library
import pandas as pd

#Create a Series
series = pd.Series(index=['Name','Age','Country'],data=['John',19,'Uganda'])

#show series
series

Name         John
Age            19
Country    Uganda
dtype: object

In [11]:
type(series)

pandas.core.series.Series

In [12]:
import pandas as pd
import numpy as np

In [13]:
data = {
    'Student_ID': range(1, 51),
    'Name': [f'Student_{i}' for i in range(1, 51)],
    'Age': np.random.randint(18, 30, 50),
    'Gender': np.random.choice(['Male', 'Female'], 50),
    'Course': np.random.choice(
        ['Cybersecurity', 'Data Science', 'Networking', 'Software Engineering'],
        50
    ),
    'GPA': np.round(np.random.uniform(2.0, 4.0, 50), 2),
    'Country': np.random.choice(
        ['Tanzania', 'Kenya', 'Uganda', 'Rwanda'],
        50
    ),
    'Graduated': np.random.choice([True, False], 50)
}

In [14]:
# Create DataFrame
df = pd.DataFrame(data)

# Display first 5 rows
print(df.head())

# Save as CSV
df.to_csv('students.csv', index=False)

# Save as Excel
df.to_excel('students.xlsx', index=False)

# Save as Parquet
df.to_parquet('students.parquet', index=False)

# Save as JSON
df.to_json('students.json', orient='records', indent=4)

print("Files saved successfully!")

   Student_ID       Name  Age  Gender         Course   GPA Country  Graduated
0           1  Student_1   21    Male   Data Science  2.91  Uganda       True
1           2  Student_2   29    Male   Data Science  2.88  Rwanda       True
2           3  Student_3   20  Female   Data Science  3.37   Kenya       True
3           4  Student_4   20  Female  Cybersecurity  2.62  Uganda       True
4           5  Student_5   19    Male     Networking  2.35  Uganda      False
Files saved successfully!

In [15]:
# Read CSV
csv_df = pd.read_csv('students.csv')

# Read Excel
excel_df = pd.read_excel('students.xlsx')

# Read Parquet
parquet_df = pd.read_parquet('students.parquet')

# Read JSON
json_df = pd.read_json('students.json')

print(csv_df.head())

   Student_ID       Name  Age  Gender         Course   GPA Country  Graduated
0           1  Student_1   21    Male   Data Science  2.91  Uganda       True
1           2  Student_2   29    Male   Data Science  2.88  Rwanda       True
2           3  Student_3   20  Female   Data Science  3.37   Kenya       True
3           4  Student_4   20  Female  Cybersecurity  2.62  Uganda       True
4           5  Student_5   19    Male     Networking  2.35  Uganda      False

# combine two dataset

In [16]:
import pandas as pd

students = pd.DataFrame({
    'Student_ID': [1, 2, 3, 4, 5],
    'Name': ['John', 'Mary', 'Peter', 'Alice', 'David'],
    'Age': [20, 21, 19, 22, 20],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male']
})

students.to_csv('students.csv', index=False)
print(students)

   Student_ID   Name  Age  Gender
0           1   John   20    Male
1           2   Mary   21  Female
2           3  Peter   19    Male
3           4  Alice   22  Female
4           5  David   20    Male

In [17]:
academic = pd.DataFrame({
    'Student_ID': [1, 2, 3, 4, 5],
    'Course': ['Cybersecurity', 'Networking', 'Data Science', 'Cybersecurity', 'Software Engineering'],
    'GPA': [3.8, 3.5, 3.9, 3.7, 3.6],
    'Year': [2, 3, 1, 4, 2]
})

academic.to_csv('academic_records.csv', index=False)
print(academic)

   Student_ID                Course  GPA  Year
0           1         Cybersecurity  3.8     2
1           2            Networking  3.5     3
2           3          Data Science  3.9     1
3           4         Cybersecurity  3.7     4
4           5  Software Engineering  3.6     2

Use merge() when datasets share a common column.

In [18]:


students = pd.read_csv('students.csv')
academic = pd.read_csv('academic_records.csv')

merged_df = pd.merge(
    students,
    academic,
    on='Student_ID',
    how='inner'
)

print(merged_df)

   Student_ID   Name  Age  Gender                Course  GPA  Year
0           1   John   20    Male         Cybersecurity  3.8     2
1           2   Mary   21  Female            Networking  3.5     3
2           3  Peter   19    Male          Data Science  3.9     1
3           4  Alice   22  Female         Cybersecurity  3.7     4
4           5  David   20    Male  Software Engineering  3.6     2

Use concat() when rows correspond in the same order.

In [19]:
students = pd.read_csv('students.csv')
academic = pd.read_csv('academic_records.csv')

concat_df = pd.concat(
    [students, academic[['Course', 'GPA', 'Year']]],
    axis=1
)

print(concat_df)

   Student_ID   Name  Age  Gender                Course  GPA  Year
0           1   John   20    Male         Cybersecurity  3.8     2
1           2   Mary   21  Female            Networking  3.5     3
2           3  Peter   19    Male          Data Science  3.9     1
3           4  Alice   22  Female         Cybersecurity  3.7     4
4           5  David   20    Male  Software Engineering  3.6     2